security:
    enable_authenticator_manager: true
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory

    password_hashers:
        harsh:
            algorithm: auto
            cost: 15

    access_control:
