version: '3.7'

services:
  php:
    build:
      context: ./.docker
      args:
        TIMEZONE: Europe/Paris
    environment:
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
    volumes:
     - ./.docker/usr/local/etc/php-fpm.z/:/usr/local/etc/php-fpm.z/
     - ./.docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./.docker/etc/nginx/conf.d/:/etc/nginx/conf.d/
     - ./.docker/etc/supervisord.conf:/etc/supervisord.conf
     - ./:/app
    ports:
     - 8081:8081
     - 8025:8025
