controllers:
    resource: '../../src/UserInterface/'
    type:     annotation

overblog_graphql_single_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/single.yaml"
    prefix: /graphql
